[versions]
kotlin = "2.3.0"

android-plugin = "8.10.0"

android-core = "1.13.1"
android-appcompat = "1.6.1"
android-material = "1.13.0"

android-lifecycle = "2.8.0"
android-lifecycle-ext = "2.2.0"

retrofit = "3.0.0"
retrofit-logging = "5.3.2"

koin = "4.1.1"
timber = "5.0.1"

[libraries]
android-core = { module = "androidx.core:core-ktx", version.ref = "android-core" }
android-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "android-appcompat" }
android-material = { module = "com.google.android.material:material", version.ref = "android-material" }

android-lifecycle-ext = { module = "androidx.lifecycle:lifecycle-extensions", version.ref = "android-lifecycle-ext" }
android-lifecycle-vm = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "android-lifecycle" }
android-lifecycle-livedata = { module = "androidx.lifecycle:lifecycle-livedata-ktx", version.ref = "android-lifecycle" }

retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
retrofit-logging = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "retrofit-logging" }

koin = { module = "io.insert-koin:koin-android", version.ref = "koin" }
timber = { module = "com.jakewharton.timber:timber", version.ref = "timber" }

[plugins]
android-app = { id = "com.android.application", version.ref = "android-plugin" }
android-lib = { id = "com.android.library", version.ref = "android-plugin" }

kotlin = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
